name: iOS Test Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Force Xcode 14.2.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '14.2.0'        
      - name: iOS iPhone 15 Pro Max
        run: >-
          xcodebuild test -project  ArcherQATest.xcodeproj -scheme ArcherQATest -destination 'platform=iOS Simulator,id=19168469-5581-4EB0-BEF1-793413CBF3FE'
      - name: testing ... iPad (10th generation)
        run: >-
          xcodebuild test -project  ArcherQATest.xcodeproj -scheme ArcherQATest -destination 'platform=iOS Simulator,id=228287AE-182F-4FA9-9C93-097B421023C4'
      - name: testing ... iOS 14 Pro Max
        run: >-
          xcodebuild test -project  ArcherQATest.xcodeproj -scheme ArcherQATest -destination 'platform=iOS Simulator,id=C2659247-054E-4121-9238-7CC7236657D1'

  
